### PR TITLE
Allow for multiple attached database files

### PR DESCRIPTION
**Pull request by johnsoftek**
This fix allows for multiple Sqlite database files to be connected. Without the fix, all SQL requests are made against the last attached database file.

### CODE REVIEW

**Comment by tushar-chauhan** [comment]
@johnsoftek Please try the base connector with multi file test case and init.js created by you. The current connector successfully executes your test scenario without this update too. This pull request doesn't show any update to the basic connector though. It's just a common test scenario which you have added and that could work with any of the other loopback connectors. This is how we create multiple DB connections in any other languages, i.e., by creating multiple connector objects.
Correct me if I am wrong, or, point me to the specifics where you think you have made an update to the connector as I might would have missed something.

**Comment by johnsoftek** [comment]
@tushar-chauhan It's true that the test runs successfully. That's because I haven't figured out how to test which Sqlite database file contains the migrated tables.

Without the fix, the connector creates both user and user2 tables in the same database file, regardless of datasource configuration.

**Comment by tushar-chauhan** [comment]
@johnsoftek I tried using the non updated base connector and ran your test case with your init.js, and it created `User` table in test.sqlite3 and `User2` in test2.sqlite3 table respectively. I appreciate your connector code cleanup and for that change please create a new pull request with only modification in base connector.
Moreover, your current pull request is a good example of how one can use this connector(or any other loopback connector) to use 2 databases simultaneously.

We can do one thing, First, I merge your new base connector pull request(which you need to create without the multi db test update). Once that is done, I will create a new branch for your multiple attached database files example, then you create a second pull request with the new branch as base and we maintain it separately. I will update the README to list that branch as an example branch to use this connector with multiple SQLite DBs.

The reason to keep it separate is simple, this is a repository for database connector and the basic init.js for tests should only contain the minimum settings(one connector instance, one DB) required to run core LoopBack tests.

Let me know if you like the idea or if you have better suggestions.

**Comment by johnsoftek** [comment]
@tushar-chauhan I am mystified. I followed your steps:
* cloned from your repo
* ran npm install
* copied .loopbackrc, test/init.js and test/multi_fie.test.js files from the pull request
* ran npm test

The image from SQLite Manager shows both user and user2 tables in the test2.sqlit3 database file.

image

**Comment by tushar-chauhan** [comment]
@johnsoftek my bad, I was running the test in your updated branch and it worked. You don't need to create a new pull request for connector cleanup, I will be taking that from this pull request itself.
I will add a new branch then where we can keep you multi file sample.

**Comment by tushar-chauhan** [comment]
@johnsoftek created a branch with the multiple file test setup. I will merge the connector update in master and update the repo in a day. Thanks for the update :smiley:

**Comment by johnsoftek** [comment]
@tushar-chauhan Thank you for the connector. It is ideal when you want an SQL solution for a Loopback project without the usual database installation/administration overhead.

**Comment by johnsoftek** [comment]
@tushar-chauhan It would be nice to have a failing test. Do you have any ideas on listing the tables in an SQLite database file?

**Comment by tushar-chauhan** [comment]
@johnsoftek You can use **.tables** or can query the **sqlite_master**  table for rows with type as **table**.

**Comment by johnsoftek** [comment]
@tushar-chauhan Yes. But is a CLI SQLite binary available within the package?

**Comment by tushar-chauhan** [comment]
@johnsoftek If you have the command line `sqlite3` tool then you can simply do 
`sqlite3 file_name.sqlite3` and you will have access to that db within terminal. Try running your queries after that. The connector may not identify such queries.

**Comment by johnsoftek** [comment]
@tushar-chauhan I wanted to have the test fail if the tables were not created in the correct database. I followed your suggestion to query sqlite_master using the connector.query(sql). It worked so now I have a pass/fail test without requiring the command line SQLite.

**Pull request merged**
